;;; init-fonts.el --- Fonts Configuration  -*- lexical-binding: t; -*-

;; Copyright (C) 2020  T_Fighting

;; Author: T_Fighting <545298210@qq.com>
;; Keywords: Fonts


;; ;; Set unicode fonts
(set-fontset-font t 'unicode "Symbola" nil 'prepend)

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>

(let ((emacs-font-size 12.5)
      (emacs-font-name "WenQuanYi Micro Hei Mono"))
  (set-frame-font (format "%s-%s" (eval emacs-font-name) (eval emacs-font-size)))
  (set-fontset-font (frame-parameter nil 'font) 'unicode (eval emacs-font-name)))

(with-eval-after-load 'org
  (defun org-buffer-face-mode-variable ()
    (interactive)
    (make-face 'width-font-face)
    (set-face-attribute 'width-font-face nil :font "等距更纱黑体 SC 15")
    (setq buffer-face-mode-face 'width-font-face)
    (buffer-face-mode))

  (add-hook 'org-mode-hook 'org-buffer-face-mode-variable))

(provide 'init-fonts)

;;; init-fonts.el ends here.
